studiometa/js-toolkit

- src/services/raf.js
This PR adds a `time` property to the props of the `raf` service.
Usage in a component:
```js
class MyComponent extends Base {
ticked({ time }) {
console.log(time);
}
}
```
Usage with the `raf` service : 
```js
import { useRaf } from '@studiometa/js-toolkit/services';
const { add, remove } = useRaf();
add('id', ({ time }) => {
console.log(time);
if (time > 1000) {
remove('id');
}
});
> Add a `time` property to the `raf` service props

- .github/workflows/npm-publish.yml
- package.json
This PR adds a Github action to publish the package to NPM on each release.
> Use Github Actions to publish to NPM on each release 

- src/abstracts/EventManager.js
- tests/EventManager.spec.js
This PR adds unit tests with Jest for the `EventManager` class. 
@studiometa/js would be interested in a live code review on how these tests were written ?
> Add unit tests for the EventManager class

- src/abstracts/Base.js
This PR converts the `$refs` and `$children` properties of a `Base` instance into getters. 
This allows us to insert refs or child components on the fly and to still get them listed in the 2 properties.
> Transform the `$refs` and `$children` properties into getters

- jest.config.js
- src/abstracts/Base/refs.js
- tests/__setup__/mockQuerySelectorAllWithScope.js
- tests/abstracts/Base/refs.spec.js
The current version ([v1.0.0-beta.3](https://github.com/studiometa/js-toolkit/releases/tag/1.0.0-beta.3)) introduced a ponyfill to resolve the refs following the `:scope` pseudo-class logic in light of some IE11 issue. The introduced ponyfill might have a negative impact on performance, so we use the `:scope` pseudo-class selector where it is available and fallback to the ponyfill version otherwise.
Ping @notjb as you found the bug 😉
> Improve the performance of the refs resolution

- packages/docs/.vitepress/config.js
- packages/docs/decorators/withBreakpointObserver.md
- packages/docs/decorators/withExtraConfig.md
- packages/docs/decorators/withIntersectionObserver.md
- packages/js-toolkit/decorators/withExtraConfig.js
- packages/tests/decorators/withExtraConfig.spec.js
This PR introduces a new `withExtraConfig(class, config)` decorator which should help to quickly create variants of an existing class.
**Add a new `toggle` ref to the modal component**
```js
import Modal from '@studiometa/js-toolkit/components/Modal';
import withExtraConfig from '@studiometa/js-toolkit/decorators/withExtraConfig';
export default withExtraConfig(Modal, { refs: ['toggle'] });
```
**Set the default styles of the modal component**
```js
import Modal from '@studiometa/js-toolkit/components/Modal';
import withExtraConfig from '@studiometa/js-toolkit/decorators/withExtraConfig';
export default withExtraConfig(Modal, {
options: {
styles: {
default: () => ({ /* ... */ }),
},
},
});
```
> Add a decorator to add extra configuration to a class

- packages/docs/api/index.md
- packages/js-toolkit/abstracts/Base/classes/Options.js
- packages/tests/abstracts/Base/classes/Options.spec.js
Add support for negated boolean option from the DOM when the default value of a boolean option is `true`.
**HTML**
```html
<div data-component="Component" data-option-no-boolean></div>
```
**JS**
```js
import Base from '@studiometa/js-toolkit';
class Component extends Base {
name: 'Component',
options: {
boolean: {
type: Boolean,
default: true,
},
},
};
mounted() {
this.$options.boolean; // false
}
}
```
> [Feature] Negated boolean option

- package-lock.json
- packages/docs/.vitepress/config.js
- packages/js-toolkit/decorators/withBreakpointObserver.js
- packages/js-toolkit/decorators/withIntersectionObserver.js
- packages/js-toolkit/decorators/withMountWhenInView.js
- packages/js-toolkit/decorators/withVue2.js
- packages/js-toolkit/package.json
- packages/tests/decorators/withIntersectionObserver.spec.js
- scripts/build.js
The `withIntersectionObserver` decorator was throwing an error when the `intersected` method was not defined on the instance. This prevented us from using the decorator by only listening to its events, for example:
```js
import { Base, withIntersectionObserver } from '@studiometa/js-toolkit';
export default class Component extends Base {
name: 'Component',
components: {
IntersectionDetector: withIntersectionObserver(Base),
},
};
onIntersectionDetectorIntersected(entries) {
// Do something with the `entries`
}
}
```
---
- Allow usage of the `withIntersectionObserver` decorator without defining the `intersected` method (#197)
- Remove the obsolete `@babel/runtime` dependency (d814c38)
- Lower the build target to `es2019` (4032a5e)
> [Feature] Allow usage of `withIntersectionObserver` with events only

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Allow usage of the `withIntersectionObserver` decorator without defining the `intersected` method (#197)
- Remove the obsolete `@babel/runtime` dependency (d814c38)
- Lower the build target to `es2019` (4032a5e)
> [Release] 2.0.0-beta.15

- package.json
- packages/docs/.vitepress/config.js
- packages/docs/api/decorators/index.md
- packages/docs/api/decorators/withFreezedOptions.md
- packages/docs/package.json
- packages/js-toolkit/decorators/index.js
- packages/js-toolkit/decorators/withFreezedOptions.js
- packages/tests/__snapshots__/index.spec.js.snap
- packages/tests/decorators/withFreezedOptions.spec.js
Add a `withFreezedOptions` decorator to make the `$options` property read-only. This can help improve performance when working with the `ticked` service hook.
> [Feature] Freezed options

- .github/workflows/release.yml
- packages/docs/api/instance-properties.md
- packages/js-toolkit/Base/managers/ServicesManager.js
- packages/tests/Base/managers/ServicesManager.spec.js
Add support for accessing a registered service props easily from within a component:  
```js
import { Base,  } from '@studiometa/js-toolkit';
class Btn extends Base {
name: 'Btn',
};
onClick() {
if (this.$services.get('resized').breakpoint === 'xxs') {
// Do something on small screens...
}
}
}
```
> [Feature] Get a service props

- .github/workflows/tests.yml
- packages/docs/.vitepress/config.js
- packages/docs/api/decorators/withScrolledInView.md
- packages/docs/utils/css/getOffsetSizes.md
- packages/js-toolkit/decorators/withScrolledInView.js
- packages/js-toolkit/utils/css/getOffsetSizes.js
- packages/js-toolkit/utils/css/index.js
- packages/tests/decorators/__snapshots__/withScrolledInView.spec.js.snap
- packages/tests/decorators/withScrolledInView.spec.js
- packages/tests/utils/__snapshots__/index.spec.js.snap
- packages/tests/utils/css/__snapshots__/getOffsetSizes.spec.js.snap
- packages/tests/utils/css/__snapshots__/index.spec.js.snap
- packages/tests/utils/css/getOffsetSizes.spec.js
- Add a `getOffsetSizes` function to get the sizes of an element without its transform (#226) 
- Fix usage of nested components using the `withScrolledInView` decorator (6b77517, #226)
> [Feature] Add a utility to get the sizes of an element without its transform

- packages/docs/.vitepress/config.js
- packages/docs/api/helpers/getDirectChildren.md
- packages/docs/api/helpers/getInstanceFromElement.md
- packages/docs/api/helpers/isDirectChild.md
- packages/js-toolkit/helpers/getDirectChildren.js
- packages/js-toolkit/helpers/index.js
- packages/tests/__snapshots__/index.spec.js.snap
- packages/tests/helpers/__snapshots__/index.spec.js.snap
- packages/tests/helpers/getDirectChildren.spec.js
- packages/tests/helpers/index.spec.js
This PR introduces a new helper `getDirectChildren` which should be used when working with nested components to easily filter direct children from nested ones. 
Example usage:
```js
import { Base, getDirectChildren, isDirectChild } from '@studiometa/js-toolkit';
import Child from './Child.js';
class Parent extends Base {
name: 'Parent',
components: {
Parent, // The parent component is recursive
Child,
},
};
onChildClick(index) {
if (getDirectChildren(this, 'Parent', 'Child').includes(this.$children.Child[index]) {
// Do something when only the `#first-child` component is clicked
}
if (isDirectChild(this, 'Parent', this.$children.Child[index], 'Child')) {
// Do something when only the `#first-child` component is clicked
}
}
}
```
```html
<div data-component="Parent">
<div …
```
> [Feature] Add a `getDirectChildren` helper

- packages/demo/src/js/components/AnimateTest.js
- packages/docs/.vitepress/config.js
- packages/docs/guide/going-further/typing-components.md
- packages/js-toolkit/Base/index.js
Until now, to be able to have autocompletion when writing components based on the `Base` class, we had to force the type of `this` for each method by using the `@this` JSDoc tag: 
```js
class Component extends Base {
name: 'Component',
refs: ['btn'],
};
/**
* @this {Component & { $refs: { btn: HTMLButtonElement } }} 
*/
mounted() {
this.$refs.btn; // HTMLButtonElement
}
}
```
This is not really practical, as we can lose types when working with child components if we do not specify the type each time we make a reference to the component's class.
This PR improves typing of class components by introducing a [type parameter](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#type-parameters) to the `Base` class.
Types for a component can now be …
> [Feature] Improve TypeScript support 

- packages/docs/api/decorators/withScrolledInView.md
- packages/js-toolkit/decorators/withScrolledInView.js
- packages/tests/decorators/__snapshots__/withScrolledInView.spec.js.snap
- packages/tests/decorators/withScrolledInView.spec.js
- **withScrolledInView** 
- Use damping on the current value instead of the progress (dd51924, #270)
As the progress value is clamped to a 0–1 interval, the damp factor and precisions value can be off when working with large elements.
For example, for an element of 100 pixels, progress from 0 to 0.1 represents 10px, but for an element of 1000 pixels, it represents 100px. To keep the same precision between the two elements, we would need to
adjust the `dampPrecision` property. By applying the damping on the sizes in pixels directly, we get rid of this problem, as the base unit is fixed in pixels.
- Fix a bug where damped values were not updated on destroy (ba93c1b, #270)
This impacted animation based on these values, which would not be finished when a component is destroyed.
> [Bugfix] Fix the `withScrolledInView` deactivation

- packages/js-toolkit/Base/managers/EventsManager.ts
This PR filters the elements of the references in the `EventManager`, so that it does not attach events to elements of the DOM that no longer exist (#278)
> [Bugfix] Filter the elements of the references in the EventsManager

- packages/demo/src/js/app.ts
- packages/docs/.vitepress/theme/components/Search.vue
- packages/docs/api/methods-hooks-events.md
- packages/docs/guide/going-further/typing-components.md
- packages/docs/guide/introduction/working-with-events.md
- packages/js-toolkit/Base/managers/EventsManager.ts
- packages/tests/Base/managers/EventsManager.spec.js
This PR introduces 2 new patterns for methods hooks, allowing to attach event listener to the `document` or the `window` object. This can be useful when needing to implement a "click outside" behavior.
- Add support for `onDocument…` and `onWindow…` hook methods (d0051fc)
- Improve regex performances in `EventsManager` (d06d9a6)
> [Feature] Add support for `onDocument<Event>` and `onWindow<Event>` hook methods

- packages/js-toolkit/utils/css/classes.js
- packages/tests/utils/css/classes.spec.js
Closes #283.
- **addClass, removeClass, toggleClass**: fix a bug where empty classes could be used (#298, fix ##283)
> [Bugfix] Fix a bug where empty classnames could be used

- packages/js-toolkit/services/drag.js
On mobile the `drop()` function was never called on touch devices on Chrome mobile when dragging.
Add `touchend` event support
> Fix drag service on touch devices

- packages/demo/src/templates/components/animate-test.twig
- packages/demo/src/templates/pages/index.twig
- packages/docs/utils/css/animate.md
- packages/js-toolkit/utils/css/animate.ts
- packages/js-toolkit/utils/tween.ts
- packages/tests/utils/css/animate.spec.js
This PR adds support for animating CSS custom properties with the `animate` function: 
```js
import { animate } from '@studiometa/js-toolkit/utils';
const element = document.querySelector('.element');
animate(element, [
{ '--red': 0 },
{ '--red': 255 },
]).start();
```
This opens up the ability to animate any CSS property using the `calc()` and `var()` CSS functions.
> [Feature] Animate CSS custom properties

- .gitignore
- package-lock.json
- packages/docs/.vitepress/config.js
- packages/docs/api/html/data-component.md
- packages/docs/api/html/data-option.md
- packages/docs/api/html/data-ref.md
- packages/docs/api/html/index.md
- packages/docs/package.json
- packages/js-toolkit/Base/utils.ts
- packages/tests/Base/utils.spec.js
Since [v2.0.0-beta.18](https://github.com/studiometa/js-toolkit/releases/tag/2.0.0-beta.18) (see #206), an HTML element can be used as root for multiple components. It was not possible yet to easily register multiple components on one element without using CSS selectors as component names. 
This feature adds support for registration of multiple components on a single HTML element via its `data-component` attribute:
```html
<div data-component="One Two Three"></div>
```
> [Feature] Add support for multiple component declaration in `data-component` attributes

- CHANGELOG.md
- packages/docs/.vitepress/theme/custom.scss
- packages/docs/api/configuration.md
- packages/docs/guide/introduction/managing-refs.md
- packages/js-toolkit/Base/managers/RefsManager.ts
- packages/js-toolkit/helpers/getClosestParent.ts
- packages/js-toolkit/utils/dom/ancestors.ts
- packages/js-toolkit/utils/dom/index.ts
- packages/js-toolkit/utils/index.ts
- packages/tests/Base/managers/RefsManager.spec.js
- packages/tests/helpers/getClosestParent.spec.js
- packages/tests/utils/__snapshots__/index.spec.js.snap
This PR adds support for refs with prefix, allowing us to place refs from a component inside another component.
Refs in nested components will not be resolved from a parent component based on their name from the `data-component` attribute.
```html
<div data-component="App">
<div data-ref="foo"></div>
<div data-direct data-ref="bar[]"></div>
<div data-direct data-prefixed data-ref="App.bar[]"></div>
<div data-component="Component">
<div data-ref="bar[]"></div>
<div data-prefixed data-ref="App.bar[]"></div>
<div data-component="App">
<div data-nested data-ref="bar[]"></div>
<div data-nested data-prefixed data-ref="App.bar[]"></div>
</div>
</div>
</div>
```
```js
class App extends Base {
name: 'App',
refs: ['bar[]'],
};
}
const apps = App.$factory('App'); …
```
> [Feature] Add support for refs with prefix

- CHANGELOG.md
- packages/js-toolkit/utils/Queue.ts
- packages/tests/utils/Queue.spec.js
This allows us to know when a task has been executed: 
```js
import { Queue, nextTick } from '@studiometa/js-toolkit/utils';
const q = new Queue(10, nextTick);
const task = () => console.log('I am a task');
q.add(task).then(() => console.log('Task has been executed'));
```
> [Feature] Queue: add support for promises

- CHANGELOG.md
- packages/js-toolkit/decorators/withScrolledInView/withScrolledInView.ts
- packages/tests/decorators/withScrolledInView/__snapshots__/withScrolledInView.spec.js.snap
The render function could be called before the `mounted` event listener, resulting in the props not being set correctly and containing som `NaN` values. Using a lazy evaluation via a getter resolves this issue.
> [Bugfix] withScrolledInView: fix props not being defined in some contexts

- CHANGELOG.md
- packages/js-toolkit/services/drag.ts
- packages/tests/services/drag.spec.js
Listen for drop events on the window to prevent the target object from sticking to the mouse when the drop occurs outside the window boundaries.
> [Bugfix] Listen for drop events on the window

- CHANGELOG.md
- packages/js-toolkit/helpers/createApp.ts
- packages/tests/helpers/createApp.spec.js
When using the `asyncChildren` feature, the components will be mounted without blocking the main thread by using a `SmartQueue` instance. This means that we can instantiate the app sooner without worrying about blocking time and might help to avoid layout shifts when mounting components.
> [Bugfix] Improve timing of app instanciation

- CHANGELOG.md
- packages/js-toolkit/utils/math/ease.ts
- packages/tests/utils/math/__snapshots__/ease.spec.js.snap
Fix the `easeInExpo`, `easeInOutExpo` and `easeOutExpo` results when the progress is equal to `0` or `1`.
> [Bugfix] Fix the `easeInExpo` value when progress is 0 or near 0

- CHANGELOG.md
- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/decorators/index.ts
- packages/js-toolkit/helpers/importOnMediaQuery.ts
- packages/js-toolkit/package.json
- packages/tests/package.json
- Fix missing extension throwing error in ESM ([055bde4](https://github.com/studiometa/js-toolkit/commit/055bde4))
> [Hotfix] 2.10.1

- CHANGELOG.md
- package-lock.json
- package.json
- **usePointer:** add support for props relative to an element ([#377](https://github.com/studiometa/js-toolkit/pull/377))
- Add a `withRelativePointer` decorator ([#377](https://github.com/studiometa/js-toolkit/pull/377))
- Fix refs name normalization when used with prefix ([#361](https://github.com/studiometa/js-toolkit/pull/361))
- Update dependencies ([#378](https://github.com/studiometa/js-toolkit/pull/378))
> [Release] 2.11.0

- CHANGELOG.md
- packages/docs/api/instance-events.md
- packages/docs/api/instance-properties.md
- packages/docs/api/methods-hooks-services.md
- packages/docs/guide/introduction/using-services.md
- packages/docs/guide/migration/v2-to-v3.md
- packages/js-toolkit/Base/managers/ServicesManager.ts
- packages/tests/Base/index.spec.ts
This PR lightens the `Base` class export by removing the default `loaded` hook.
> [Feature] Remove the `loaded` hook

- .prettierignore
- CHANGELOG.md
- packages/docs/api/methods-hooks-services.md
- packages/js-toolkit/decorators/withScrolledInView/withScrolledInView.ts
- packages/js-toolkit/services/scroll.ts
- packages/js-toolkit/utils/css/getOffsetSizes.ts
- packages/js-toolkit/utils/scrollTo.ts
- packages/tests/__utils__/happydom.ts
- packages/tests/utils/scrollTo.spec.ts
The `pageXOffset` and `pageYOffset` properties of the `window` object are [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX#notes) and currently only aliases for the `scrollX` and `scrollY` properties. This PR refactor usage of the legacy properties in favor of their current version.
> [Feature] Migrate legacy `pageXOffset` and `pageYOffset` to their equivalent `scrollX` and `scrollY` 

- CHANGELOG.md
- packages/js-toolkit/decorators/withScrolledInView/withScrolledInView.ts
> [Feature] Remove deprecated methods from the `withScrolledInView` decorator

- CHANGELOG.md
- packages/docs/guide/migration/v2-to-v3.md
- packages/docs/utils/index.md
- packages/docs/utils/scrollTo.md
- packages/js-toolkit/utils/index.ts
- packages/js-toolkit/utils/scrollTo.ts
- packages/tests/__utils__/happydom.ts
- packages/tests/__utils__/scroll.ts
- packages/tests/utils/scrollTo.spec.ts
> [Feature] `scrollTo` enhancement

- CHANGELOG.md
- README.md
- packages/docs/api/configuration.md
- packages/docs/guide/introduction/managing-options.md
- packages/js-toolkit/Base/managers/OptionsManager.ts
- packages/tests/Base/managers/OptionsManager.spec.ts
This PR adds support for defining an option default value with a function for all types of options. The function is called with the current instance as only parameter, allowing for advanced management of default values. 
```js {9-18}
import { Base } from '@studiometa/js-toolkit';
class Player extends Base {
name: 'Player',
options: {
type: {
type: String,
default(player) {
switch (player.$el.constructor) {
case HTMLVideoElement:
return 'video';
case HTMLAudioElement:
return 'audio';
default:
return 'unknown';
}
},
},
},
};
}
```
> [Feature] Add support for defining an option default value with a function

- CHANGELOG.md
- packages/docs/api/helpers/getInstances.md
- packages/js-toolkit/Base/Base.ts
- packages/js-toolkit/Base/utils.ts
- packages/js-toolkit/index.ts
- packages/tests/Base/utils.spec.ts
- packages/tests/__snapshots__/index.spec.ts.snap
- scripts/add-utils-export.js
This PR improves the `getInstances` helper with the following: 
- only return instances of mounted components (destroyed components are ignored)
- returns all instances of all components if no parameter is given
> [Feature] Improve the `getInstances` helper

- CHANGELOG.md
- packages/docs/api/helpers/createApp.md
- packages/docs/api/html/index.md
- packages/js-toolkit/Base/features.ts
- packages/js-toolkit/Base/managers/EventsManager.ts
- packages/js-toolkit/Base/managers/OptionsManager.ts
- packages/js-toolkit/Base/managers/RefsManager.ts
- packages/js-toolkit/Base/managers/ResponsiveOptionsManager.ts
- packages/js-toolkit/Base/utils.ts
- packages/js-toolkit/decorators/withBreakpointObserver.ts
- packages/js-toolkit/helpers/createApp.ts
- packages/tests/Base/features.spec.ts
- packages/tests/Base/utils.spec.ts
- packages/tests/__utils__/mockFeatures.ts
- packages/tests/helpers/createApp.spec.ts
#492 
This PR adds the possibility to configure the HTML attributes used to define components, refs and options. The defaults are still `data-component`, `data-ref` and `data-option-...`, but they can now be configured with [the `createApp()` helper](https://js-toolkit.studiometa.dev/api/helpers/createApp.html).
> [Feature] Configurable attributes

- CHANGELOG.md
- packages/docs/api/methods-hooks-events.md
- packages/docs/guide/introduction/working-with-events.md
- packages/docs/guide/migration/v2-to-v3.md
- packages/js-toolkit/Base/managers/EventsManager.ts
- packages/tests/Base/managers/EventsManager.spec.ts
#297
This PR refactors the parameters given to the `on...` callback function to a more consistent API. See #297 for the why. 
With this PR, all `on...` methods will receive a single `context` parameter which is an object of the following type: 
```ts
export type EventManagerCallbackParams = {
event: Event;
args: Array<any>;
index: number;
target: Element | Base | Promise<Base> | typeof window | typeof document;
};
```
Usage will be:
```ts
onClick({ event }) {
event.preventDefault();
}
onCustomEvent({ event, args: [arg1, arg2], target }) {
console.log(target === this); // true
}
onChildClick({ event, args: [arg1, arg2], target, index }) {
const currentChild = target;
const currentChildIndex = index;
}
onRefClick({ event, target, index }) {
const currentRef = target;
const currentRefIndex = …
```
> [Feature] Refactor event callbacks parameters ⚠️

- CHANGELOG.md
- packages/docs/api/instance-methods.md
- packages/docs/guide/introduction/working-with-events.md
- packages/docs/guide/migration/v2-to-v3.md
- packages/js-toolkit/Base/Base.ts
- packages/js-toolkit/Base/managers/ChildrenManager.ts
- packages/js-toolkit/Base/utils.ts
- packages/js-toolkit/decorators/withBreakpointManager.ts
- packages/js-toolkit/decorators/withBreakpointObserver.ts
- packages/js-toolkit/decorators/withMountOnMediaQuery.ts
- packages/js-toolkit/decorators/withMountWhenInView.ts
- packages/js-toolkit/helpers/createApp.ts
- packages/tests/Base/Base.spec.ts
- packages/tests/Base/features.spec.ts
- packages/tests/Base/managers/ChildrenManager.spec.ts
- packages/tests/Base/managers/EventsManager.spec.ts
- packages/tests/Base/managers/ServicesManager.spec.ts
- packages/tests/decorators/withBreakpointManager.spec.ts
- packages/tests/decorators/withDrag.spec.ts
- packages/tests/decorators/withIntersectionObserver.spec.ts
- packages/tests/decorators/withRelativePointer.spec.ts
- packages/tests/helpers/getClosestParent.spec.ts
- packages/tests/helpers/getDirectChildren.spec.ts
No issue.
This PR makes the `$mount`, `$update`, `$destroy` and `$terminate` method async. With the introduction of the non-blocking queue in #427, making these methods async will help us wait or not for the end of the different lifecycle action.
> [Feature] Make the lifecycle methods async ⚠️

- CHANGELOG.md
- packages/docs/guide/migration/v2-to-v3.md
- packages/js-toolkit/Base/Base.ts
- packages/js-toolkit/Base/managers/EventsManager.ts
- packages/js-toolkit/Base/utils.ts
- packages/tests/__utils__/h.ts
#342
This PR reduces the noise of warnings when the `on...` methods are bound to their specific targets. It also removes the fallback binding of an event to a target that can not emit this event.
> [Bugfix] Fix warning for and listening to unconfigured events

- CHANGELOG.md
- packages/docs/.vitepress/config.js
- packages/docs/.vitepress/theme/custom.scss
- packages/docs/api/instance-methods.md
- packages/docs/guide/migration/v2-to-v3.md
- packages/docs/index.md
- packages/docs/utils/string/dashCase.md
- packages/docs/utils/string/lowerCase.md
- packages/docs/utils/string/snakeCase.md
- packages/js-toolkit/Base/Base.ts
- packages/js-toolkit/Base/utils.ts
- packages/tests/Base/managers/EventsManager.spec.ts
- packages/tests/Base/utils.spec.ts
#508
Custom events are now dispatched on the root element instead of the instance itself. 
This is considered a breaking change for the following reason:
- The `Base` class no longer extends the `EventTarget` class 
- Custom event emitted might conflict with native events
> [Feature] Dispatch custom events on the root element

- CHANGELOG.md
- packages/js-toolkit/Base/managers/EventsManager.ts
- packages/tests/Base/managers/EventsManager.spec.ts
#515 
This PR fixes #515 by comparing the current component root element with `event.currentTarget` instead of `event.target`.
> [Bugfix] trigger event hook bubbling event

- packages/js-toolkit/services/drag.ts
- packages/tests/services/drag.spec.ts
#532 
See #532 for details on the bug.
The bug is fixed by correctly resetting the `previousEvent` variable when the drop occurs in a drag and drop interaction.
> [Bugfix] Fix the `useDrag` delta props not being correct on multiple drag actions

- CHANGELOG.md
- packages/js-toolkit/services/AbstractService.ts
- packages/js-toolkit/services/DragService.ts
- packages/js-toolkit/services/KeyService.ts
- packages/js-toolkit/services/LoadService.ts
- packages/js-toolkit/services/PointerService.ts
- packages/js-toolkit/services/ResizeService.ts
- packages/js-toolkit/services/ScrollService.ts
- packages/js-toolkit/services/utils.ts
- packages/tests/services/AbstractService.spec.ts
No issue.
This PR refactors the way services are configured by replacing implementation of the `init` and `kill` methods with configurations.
> [Feature] Refactor services configuration

- CHANGELOG.md
- packages/demo/package.json
- packages/demo/src/js/app.ts
- packages/demo/src/templates/pages/drag.twig
- packages/js-toolkit/services/AbstractService.ts
- packages/js-toolkit/services/DragService.ts
- packages/tests/services/DragService.spec.ts
#538
This PR adds an early return to the `drop()` method of the `DragService` class to prevent calling it before any drag interaction has happened.
> [Bugfix] Fix drag service triggering out of context drop action

- packages/js-toolkit/services/AbstractService.ts
- packages/js-toolkit/services/DragService.ts
- packages/js-toolkit/services/KeyService.ts
- packages/js-toolkit/services/LoadService.ts
- packages/js-toolkit/services/PointerService.ts
- packages/js-toolkit/services/ResizeService.ts
- packages/js-toolkit/services/ScrollService.ts
No issue.
Using the `document` and `window` variable in static properties meant they must be defined when a service is imported. This is fixed by always using a function to return the target of the events in a service config.
> [Bugfix] Fix importing the services in SSR context

- CHANGELOG.md
- packages/docs/api/instance-properties.md
- packages/js-toolkit/Base/Base.ts
- packages/js-toolkit/Base/managers/AbstractManager.ts
- packages/js-toolkit/Base/managers/ChildrenManager.ts
- packages/js-toolkit/Base/managers/EventsManager.ts
- packages/js-toolkit/Base/managers/OptionsManager.ts
- packages/js-toolkit/Base/managers/RefsManager.ts
- packages/js-toolkit/Base/managers/ResponsiveOptionsManager.ts
- packages/js-toolkit/Base/managers/ServicesManager.ts
- packages/tests/Base/Base.spec.ts
- packages/tests/Base/managers/ResponsiveOptionsManager.spec.ts
- packages/tests/decorators/withBreakpointObserver.spec.ts
- packages/tests/decorators/withMountWhenInView.spec.ts
- packages/tests/decorators/withResponsiveOptions.spec.ts
- packages/tests/helpers/importOnMediaQuery.spec.ts
- packages/tests/helpers/importWhenPrefersMotion.spec.ts
- packages/tests/helpers/importWhenVisible.spec.ts
- packages/tests/utils/loadElement.spec.ts
#542 
This PR fixes the `$mount()` and `$update()` methods never resolving when using async components.
Async components were added to the list of component that should be awaited before mounting or updating the parent, creating some long hanging promises that might never resolve. This commit switch back to the previous behavior of not waiting for async components to be resolved before considering all children mounted (which is the point of async components).
It also adds a `$config` property on each `Base` instance to be able to read the resolved and merged configuration of the current component (based on the current class static config as well as its ancestors').
> [Bugfix] Fix awaiting the $mount and $update methods

- CHANGELOG.md
- package-lock.json
- package.json
- packages/demo/package.json
- packages/js-toolkit/helpers/createApp.ts
- packages/js-toolkit/services/AbstractService.ts
- packages/tests/helpers/createApp.spec.ts
#552 
To avoid rogue instances that should not be kept alive, this PR adds a new mutation observer callback to destroy instances whose root element is no longer in the DOM.
> [Feature] Terminate instances whose root element has been removed from the DOM

- CHANGELOG.md
- packages/js-toolkit/decorators/withScrolledInView/withScrolledInView.ts
- packages/js-toolkit/services/RafService.ts
- packages/tests/decorators/withScrolledInView/withScrolledInView.spec.ts
Fix: #607
This PR refactors the `withScrolledInView` decorator to reuse the existing `domScheluder` scheduler instead of a custom one.
> [Feature] Use the existing `domScheduler` for the `withScrolledInView` decorator

- CHANGELOG.md
- packages/docs/utils/cache.md
- packages/js-toolkit/services/ResizeService.ts
- packages/tests/decorators/withBreakpointObserver.spec.ts
- packages/tests/services/ResizeService.spec.ts
No issue.
The `matchMedia` function is really slow in Safari, adding a cache will improve performance when accessing any of the breakpoint props from the resize service. 
See https://jsbench.me/kpm6eyv92r/1 in different browsers.
> [Feature] Improve breakpoint performance

- CHANGELOG.md
- packages/js-toolkit/services/DragService.ts
No issue.
Follow up of #618 to re-add static access to the drag service `MODES`.
> [Feature] Enable static access to the drag service modes

- CHANGELOG.md
- packages/js-toolkit/utils/scrollTo.ts
- packages/tests/utils/scrollTo.spec.ts
This PR fixes a bug when scrolling on a target that implements a smooth scroll behavior.
> [Bugfix] Fix `scrollTo` scroll behavior

- CHANGELOG.md
- packages/docs/api/services/useRaf.md
- packages/js-toolkit/services/RafService.ts
- packages/tests/services/RafService.spec.ts
This PR adds a new `delta` props to the `useRaf()` service.
```js
import { useRaf } from '@studiometa/js-toolkit';
useRaf().add('key', (props) => {
console.log(props.delta); // time elapsed since the last call
});
```
> [Feature] Add a `delta` props to the RafService

- CHANGELOG.md
- packages/js-toolkit/utils/css/transform.ts
- packages/tests/utils/css/transform.spec.ts
#658 
This PR fixes a bug where the `transform` utility function would throw if it receives `null` or `undefined` as its first parameter.
> [Bugfix] `transform` throws if element is `null` or `undefined`

- CHANGELOG.md
- packages/demo/src/js/components/AnimateTest.js
- packages/demo/src/templates/pages/index.twig
- packages/docs/.vitepress/config.ts
- packages/docs/utils/math/smoothTo.md
- packages/docs/utils/math/spring.md
- packages/docs/utils/math/wrap.md
- packages/docs/utils/tween.md
- packages/js-toolkit/utils/math/index.ts
- packages/js-toolkit/utils/math/smoothTo.ts
- packages/js-toolkit/utils/math/spring.ts
- packages/js-toolkit/utils/math/wrap.ts
- packages/js-toolkit/utils/tween.ts
- packages/tests/utils/index.spec.ts
- packages/tests/utils/math/smoothTo.spec.ts
- packages/tests/utils/math/spring.spec.ts
- packages/tests/utils/math/wrap.spec.ts
- packages/tests/utils/tween.spec.ts
No issue
This PR adds some utility functions for animation and add support for [spring physics](https://www.joshwcomeau.com/animation/a-friendly-introduction-to-spring-physics/) to the `tween` and `animate` functions. 
- `spring`: like the `damp` function, but for [spring animations](https://www.joshwcomeau.com/animation/a-friendly-introduction-to-spring-physics/)
- `wrap`: like the `clamp` function, but with a loop 
- `smoothTo`: easier usage of the `damp` and `spring` functions, less boilerplate
**spring**
```js
import { spring } from '@studiometa/js-toolkit/utils';
let value = 0;
let velocity = 0;
[value, velocity] = spring(100, value, velocity);
```
**wrap**
```js
import { wrap } from '@studiometa/js-toolkit/utils';
let value = 0;
window.addEventListener('wheel', (event) => {
value = …
```
> [Feature] Animation utils
