studiometa/js-toolkit

- .github/workflows/release.yml
- package-lock.json
- package.json
- Fix the publication of the package (1812414)
> Hotfix/1.0.0 beta.5

- src/utils/math/clamp.js
- src/utils/math/clamp01.js
- src/utils/math/index.js
- tests/utils/math/clamp.spec.js
- tests/utils/math/clamp01.spec.js
- tests/utils/math/index.spec.js
> Add clamp math functions

- packages/js-toolkit/abstracts/Base/events.js
- packages/tests/abstracts/Base/events.spec.js
> Fix event method binding on async children components

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/js-toolkit/services/drag.js
- packages/tests/package.json
- Fix a warning when not using passive event listeners (2c8679f)
- Update dependencies (0d160ad)
> [Hotfix] 1.6.2

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Add support for negated boolean option with true as default value with the `data-option-no-<boolean-option-name>` attribute pattern (#143)
> [Release] 1.7.0

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
Fixed
- Fix tree-shaking (78b7144)
> [Hotfix] 1.7.1

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/js-toolkit/utils/history.js
- packages/tests/__setup__/ResizeObserver.js
- packages/tests/__setup__/mockBreakpoints.js
- packages/tests/__setup__/mockQuerySelectorAllWithScope.js
- packages/tests/package.json
- packages/tests/utils/history.server.spec.js
- packages/tests/utils/nextFrame.spec.js
- Fix usage of `objectToURLSearchParams` server side (91f78a8)
- Improve `nextFrame` tests (9ecf91b)
> [Hotfix] 1.7.2

- packages/docs/api/instance-properties.md
This PR Adds a proper link to an other page of the documentation.
✌️
> Add the proper link to config.options doc

- .github/workflows/release.yml
- packages/docs/.vitepress/config.js
- packages/docs/guide/migration/v1-to-v2.md
> [Feature] Add a migration guide to the documentation

- .github/workflows/release.yml
- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Fix release action (f8895e7)
> [Hotfix] 2.0.0-beta.2

- .github/workflows/release.yml
- .github/workflows/tests.yml
- Fix changelog generation in release action (8226d9a)
- Improve GitHub actions performances (746c4d4)
> [Hotfix] 2.0.0-beta.3 

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/js-toolkit/utils/scrollTo.js
- packages/tests/package.json
- packages/tests/utils/scrollTo.spec.js
- Fix the `scrollTo`utility calculations (8c03043)
- Update NPM dependencies (#171)
> [Release] 2.0.0 beta.5

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/Base/index.js
- packages/js-toolkit/package.json
- packages/tests/package.json
> [Hotfix] 2.0.0 beta.8

- packages/docs/api/decorators/withBreakpointManager.md
- packages/docs/api/decorators/withBreakpointObserver.md
- packages/docs/api/decorators/withIntersectionObserver.md
- packages/docs/api/decorators/withMountWhenInView.md
- packages/docs/api/decorators/withScrolledInView.md
- packages/js-toolkit/decorators/withScrolledInView.js
- Add support for custom `IntersectionObserver` options for the `withScrolledInView` decorator (#185)
- Add missing doc for decorators
> [Bugfix] Scrolled in view trigger offset

- package-lock.json
- package.json
- packages/docs/.vitepress/theme/components/App.vue
- packages/docs/.vitepress/theme/components/Layout.vue
- packages/docs/.vitepress/theme/components/NavBarTitle.vue
- packages/docs/.vitepress/theme/components/Search.vue
- packages/docs/.vitepress/theme/components/SearchResults.vue
- packages/docs/.vitepress/theme/composables/useAllLinks.ts
- packages/docs/.vitepress/theme/custom.scss
- packages/docs/.vitepress/theme/index.js
- packages/docs/package.json
- packages/docs/scripts/patch-vue-kbar.js
- packages/docs/tailwind.config.js
- packages/docs/utils/math/ease.md
Add a search bar to the doc.
Close #99.
> [Feature] Add a searchbar to the doc

- packages/docs/guide/introduction/managing-refs.md
There is still rewording to do but it should be good enough. Feel free to propose things to make it better!
> Add managing refs section

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/js-toolkit/utils/scrollTo.js
- packages/tests/package.json
- Fix the calculation of the scroll target offsets (1e072a1)
> [Hotfix] 2.0.0 beta.11

- package-lock.json
- package.json
- packages/docs/utils/collision/collideCircleCircle.md
- packages/docs/utils/math/ease.md
- packages/js-toolkit/package.json
- packages/js-toolkit/utils/collide/boundingRectToCircle.js
- packages/js-toolkit/utils/index.js
- packages/tests/utils/__snapshots__/index.spec.js.snap
- scripts/build.js
- tsconfig.build.json
- tsconfig.json
- Add support for CommonJS usage (#193)
> [Feature] Add support for CommonJS usage

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Add support for CommonJS usage (#193) 
- Improve docs (#168)
- Add a missing export (213f4ce)
> [Release] 2.0.0-beta.12

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- scripts/build.js
- Fix extensions of built files in CJS format (56a6ee5)
> [Hotfix] 2.0.0 beta.13

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- scripts/build.js
> [Hotfix] 2.0.0 beta.14

- packages/docs/api/configuration.md
- packages/docs/guide/introduction/managing-options.md
First draft of the managing options section of the guide.
> Add managing options content

- package-lock.json
- package.json
- packages/demo/package.json
- packages/demo/src/templates/pages/index.twig
- packages/docs/api/services/useDrag.md
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/js-toolkit/services/drag.js
- packages/tests/package.json
- packages/tests/services/drag.spec.js
- packages/tests/services/drag2.spec.js
- Fix links and images usage in drag element (5c42eb5, #203)
- Add the `dragTreshold` option to the `useDrag` service (da7c20b, #203)
> [Hotfix] 2.0.0-beta.16

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/decorators/withMountWhenInView.js
- packages/js-toolkit/package.json
- packages/js-toolkit/services/drag.js
- packages/tests/package.json
- **Services (drag):** remove a forbidden `preventDefault()` call (the event is passive) (a275700)
> [Release] 2.0.0 beta.17

- packages/docs/.vitepress/config.js
- packages/docs/guide/introduction/managing-options.md
- packages/docs/utils/css/addClass.md
- packages/docs/utils/css/addStyle.md
- packages/docs/utils/css/removeClass.md
- packages/docs/utils/css/removeStyle.md
- packages/docs/utils/css/toggleClass.md
- packages/js-toolkit/utils/css/classes.js
- packages/js-toolkit/utils/css/index.js
- packages/js-toolkit/utils/css/styles.js
- packages/js-toolkit/utils/css/transition.js
- packages/js-toolkit/utils/index.js
- packages/tests/utils/__snapshots__/index.spec.js.snap
- packages/tests/utils/css/__snapshots__/index.spec.js.snap
- packages/tests/utils/css/__snapshots__/transition.spec.js.snap
- packages/tests/utils/css/index.spec.js
- packages/tests/utils/css/transition.spec.js
- Add exports for the class and style utility functions 
- Add support for array of classes for the `transition` function object parameter
- Improve types of the `transition` function 
---
> [Feature] Exports class and style utility functions and improve transition types

- packages/docs/.vitepress/config.js
- packages/docs/utils/nextMicrotask.md
- packages/docs/utils/nextTick.md
- packages/js-toolkit/utils/index.js
- packages/js-toolkit/utils/nextFrame.js
- packages/js-toolkit/utils/nextMicrotask.js
- packages/js-toolkit/utils/nextTick.js
- packages/tests/utils/__snapshots__/index.spec.js.snap
- packages/tests/utils/__snapshots__/nextTick.spec.js.snap
- packages/tests/utils/nextTick.spec.js
- Add `nextTick` schedule utility function
- Add `nextMicrotask` schedule utility function
- `nextFrame` waits only for one frame instead of chaining two `requestAnimationFrame` calls
> [Feature] Scheduling helpers

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
This should be the latest beta version 🤞 
- Add support for multiple instance on a single HTML element (#206) 
- Add support for optional root element for the `createApp` helper (4bee699)
- Add `nextTick` schedule utility function (#207)
- Add `nextMicrotask` schedule utility function (#207)
- Add exports for the class and style utility functions (#208)
- Add support for array of classes for the `transition` function object parameter (#208)
- `nextFrame` waits only for one frame instead of chaining two `requestAnimationFrame` calls (#207)
- Improve types of the `transition` function (#208)
> [Release] 2.0.0-beta.18

- packages/docs/api/configuration.md
- packages/docs/guide/introduction/managing-options.md
- packages/js-toolkit/Base/managers/OptionsManager.js
- packages/tests/Base/managers/OptionsManager.spec.js
- Add support for control over `Array` and `Object` options mergeability (#214)
> [Feature] Add support for control over `Array` and `Object` options mergeability

- .github/workflows/release.yml
- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/decorators/withFreezedOptions.js
- packages/js-toolkit/decorators/withVue2.js
- packages/js-toolkit/package.json
- packages/tests/decorators/__snapshots__/withVue2.spec.js.snap
- packages/tests/decorators/withVue2.spec.js
- packages/tests/package.json
- Add support for `vueConfig` as getter (#190, #217, ebfa90d)
- Allow configuration of the freezed options (#217, a01daf3)
- Fix release of RC version with the `next` tag (#217, 4a459a5)
> [Hotfix] 2.0.0 rc.2

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/decorators/withFreezedOptions.js
- packages/js-toolkit/package.json
- packages/js-toolkit/services/scroll.js
- packages/js-toolkit/utils/css/transition.js
- packages/tests/decorators/withFreezedOptions.spec.js
- packages/tests/package.json
- Fix usage of the scroll service props (8d34ecf)
- Fix transition failing to add the active classes (63f4476)
- Allow overriding options with the `withFreezedOptions` decorator (f1fd094)
> [Hotfix] 2.0.1

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/js-toolkit/utils/css/animate.js
- packages/js-toolkit/utils/math/createEases.js
- packages/js-toolkit/utils/math/ease.js
- packages/js-toolkit/utils/math/index.js
- packages/tests/package.json
* Fix `ease` export to contain only easing functions (d6720f9)
> [Hotfix] 2.2.1

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/guide/going-further/typing-components.md
- packages/docs/package.json
- packages/js-toolkit/Base/index.js
- packages/js-toolkit/Base/managers/EventsManager.js
- packages/js-toolkit/helpers/getDirectChildren.js
- packages/js-toolkit/index.js
- packages/js-toolkit/package.json
- packages/tests/package.json
- Improve new types introduced in [v2.4.2](https://github.com/studiometa/js-toolkit/releases/tag/2.4.2) (1df4452)
> [Hotfix] 2.4.3

- .github/workflows/release.yml
- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Fix release GitHub Action (20998cf)
> [Release] 2.4.5

- packages/js-toolkit/decorators/withFreezedOptions.ts
- Fix a recursive type definition (90fdf96)
> [Bugfix] Fix a recursive type definition

- .github/workflows/release.yml
- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Fix a recursive type definition (90fdf96, #280)
- Fix a bug where refs could be undefined (#279, fixes #278)
> [Release] 2.4.6

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Fix exports definition (d4efde9)
> [Hotfix] 2.4.7

- packages/js-toolkit/services/drag.js
- packages/tests/decorators/withDrag.spec.js
- packages/tests/services/__snapshots__/drag.spec.js.snap
- packages/tests/services/drag.spec.js
The order in which events were fired when using the pointer service for the drag service was creating glitches and jumps on touch devices. This PR fixes this.
- Fix drag service with touch events (#290)
> [Bugfix] Fix drag service with touch events

- .github/workflows/tests.yml
- scripts/build.js
- Ship ESNext JavaScript (#296)
- Add sourcemaps (#296)
> [Feature] Ship esnext code

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/.vitepress/theme/components/Search.vue
- packages/docs/package.json
- packages/js-toolkit/Base/managers/ServicesManager.ts
- packages/js-toolkit/package.json
- packages/tests/Base/__snapshots__/index.spec.js.snap
- packages/tests/__snapshots__/index.spec.js.snap
- packages/tests/decorators/__snapshots__/withScrolledInView.spec.js.snap
- packages/tests/decorators/__snapshots__/withVue2.spec.js.snap
- packages/tests/helpers/__snapshots__/index.spec.js.snap
- packages/tests/package.json
- packages/tests/services/__snapshots__/drag.spec.js.snap
- packages/tests/utils/__snapshots__/index.spec.js.snap
- packages/tests/utils/__snapshots__/nextTick.spec.js.snap
- packages/tests/utils/css/__snapshots__/getOffsetSizes.spec.js.snap
- packages/tests/utils/css/__snapshots__/index.spec.js.snap
- packages/tests/utils/css/__snapshots__/transition.spec.js.snap
- packages/tests/utils/math/__snapshots__/index.spec.js.snap
- patches/@bytebase+vue-kbar+0.1.8.patch
- Fix return function of the raf service not executing (#304, 22d92d7)
- Update NPM dependencies (#304, dbbd1a9)
> [Hotfix] 2.6.2

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/js-toolkit/services/drag.js
- packages/js-toolkit/utils/scrollTo.js
- packages/tests/package.json
> [Release] 2.6.3

- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- **service(drag):** fix drag service on chrome when using touch by adding `touchend` event (#306)
> [Release] 2.6.4

- CHANGELOG.md
- packages/demo/src/js/app.ts
- packages/demo/src/js/components/ScrolledInViewOffset.js
- packages/demo/src/templates/pages/scrolled-in-view-offset.twig
- packages/docs/.vitepress/theme/components/PreviewIframe.vue
- packages/docs/.vitepress/theme/composables/useObserver.ts
- packages/docs/api/configuration.md
- packages/docs/api/decorators/withScrolledInView.md
- packages/docs/api/decorators/withScrolledInView/demo.md
- packages/docs/api/decorators/withVue2.md
- packages/docs/api/html/data-component.md
- packages/docs/api/html/data-option.md
- packages/docs/api/html/data-ref.md
- packages/docs/api/html/index.md
- packages/docs/tailwind.config.cjs
- packages/js-toolkit/decorators/index.ts
- packages/js-toolkit/decorators/withScrolledInView/index.ts
- packages/js-toolkit/decorators/withScrolledInView/types.ts
- packages/js-toolkit/decorators/withScrolledInView/utils.ts
- packages/js-toolkit/decorators/withScrolledInView/withScrolledInView.ts
- packages/js-toolkit/utils/css/getOffsetSizes.ts
- packages/js-toolkit/utils/is.ts
- packages/tests/decorators/withScrolledInView/__snapshots__/withScrolledInView.spec.js.snap
- packages/tests/decorators/withScrolledInView/utils.test.ts
- packages/tests/decorators/withScrolledInView/withScrolledInView.spec.js
- packages/tests/utils/css/getOffsetSizes.spec.js
- packages/tests/utils/is.spec.js
See the [demo page](https://deploy-preview-321--studiometa-js-toolkit-demo.netlify.app/scrolled-in-view-offset.html) for an example of how the `offset` option can be used.
> [Feature] Add support for an offset option for the withScrolledInView decorator

- CHANGELOG.md
- packages/docs/api/instance-methods.md
- packages/js-toolkit/Base/Base.ts
- packages/tests/Base/__snapshots__/index.spec.js.snap
- packages/tests/Base/index.spec.js
- **Base:**
- Add the `$warn()` helper ([1071c75](https://github.com/studiometa/js-toolkit/commit/1071c75))
> [Feature] Warning helper

- CHANGELOG.md
- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Loosen the Vue version constraint ([da22e8a](https://github.com/studiometa/js-toolkit/commit/da22e8a))
> [Hotfix] 2.10.3

- CHANGELOG.md
- packages/js-toolkit/Base/managers/RefsManager.ts
- packages/tests/Base/managers/EventsManager.spec.js
> [Bugfix] Fix refs name normalization when used with prefix

- CHANGELOG.md
- packages/docs/api/helpers/createApp.md
- packages/docs/api/services/useResize.md
- packages/docs/guide/migration/v2-to-v3.md
- packages/js-toolkit/Base/features.ts
- packages/js-toolkit/helpers/createApp.ts
- packages/js-toolkit/services/index.ts
- packages/js-toolkit/services/resize.ts
- packages/tests/Base/managers/ResponsiveOptionsManager.spec.js
- packages/tests/__utils__/matchMedia.js
- packages/tests/decorators/withBreakpointManager.spec.js
- packages/tests/decorators/withBreakpointObserver.spec.js
- packages/tests/decorators/withMountOnMediaQuery.spec.js
- packages/tests/decorators/withMountWhenPrefersMotion.spec.js
- packages/tests/helpers/importOnMediaQuery.spec.js
- packages/tests/helpers/importWhenPrefersMotion.spec.js
- packages/tests/services/resize.spec.js
This PR adds support for defining screens definition with the `createApp` helper.
Fix #264.
> [Feature] Resize screens definition

- CHANGELOG.md
- packages/js-toolkit/Base/Base.ts
Remove unnecessary manager instance type check.
> [Feature] Remove unnecessary manager check

- CHANGELOG.md
- packages/docs/api/decorators/withScrolledInView/demo.md
- packages/docs/api/instantiation.md
- packages/docs/api/static-methods.md
- packages/docs/guide/index.md
- packages/docs/guide/recipes/counter-component/index.md
- packages/docs/guide/recipes/scroll-linked-animation/index.md
- packages/js-toolkit/Base/Base.ts
- packages/tests/Base/index.spec.ts
> [Feature] Rename the static `$factory` to `$register` and make its single argument optional

- CHANGELOG.md
- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/docs/utils/tween.md
- packages/js-toolkit/package.json
- packages/tests/package.json
> [Feature] Update dependencies

- .eslintrc.cjs
- CHANGELOG.md
- package-lock.json
- package.json
- packages/demo/meta.config.mjs
- packages/demo/package.json
- packages/demo/src/js/components/BreakPointManagerDemo/BreakpointManagerDemoDesktop.js
- packages/demo/src/js/components/BreakPointManagerDemo/BreakpointManagerDemoMobile.js
- packages/demo/src/js/components/BreakPointManagerDemo/BreakpointManagerDemoTablet.js
- packages/docs/.vitepress/config.js
- packages/docs/package.json
- packages/docs/utils/index.md
- packages/docs/utils/math/createRange.md
- packages/js-toolkit/Base/managers/ChildrenManager.ts
- packages/js-toolkit/decorators/withIntersectionObserver.ts
- packages/js-toolkit/package.json
- packages/js-toolkit/utils/math/createRange.ts
- packages/js-toolkit/utils/math/index.ts
- packages/js-toolkit/utils/random.ts
- packages/tests/package.json
- packages/tests/utils/__snapshots__/index.spec.ts.snap
- packages/tests/utils/math/createRange.spec.ts
- packages/tests/utils/random.spec.ts
-  Add a `createRange` utility function ([2cb2bac](https://github.com/studiometa/js-toolkit/commit/2cb2bac))
- 9722d74 Fix an import path ([9722d74](https://github.com/studiometa/js-toolkit/commit/9722d74))
> [Release] 3.0.0-alpha.2

- CHANGELOG.md
- packages/docs/api/services/useScroll.md
- packages/js-toolkit/services/scroll.ts
> [Feature] Shorthand props on the scroll service for easier destructuring

- .github/workflows/release.yml
- CHANGELOG.md
- package-lock.json
- package.json
- packages/demo/package.json
- packages/docs/package.json
- packages/js-toolkit/package.json
- packages/tests/package.json
- Fix the publish action ([#493](https://github.com/studiometa/js-toolkit/pull/493), [32cc4fe](https://github.com/studiometa/js-toolkit/commits/32cc4fe))
> [Hotfix] 2.12.1

- CHANGELOG.md
- packages/js-toolkit/Base/managers/EventsManager.ts
- packages/tests/Base/managers/EventsManager.spec.ts
#511 
This PR improves the way `on...` methods are called when an event is dispatched on a child component.
> [Bugfix] Fix conflicts with event callbacks for multiple components on a single element

- CHANGELOG.md
- package-lock.json
- packages/js-toolkit/Base/managers/EventsManager.ts
- packages/js-toolkit/decorators/withBreakpointObserver.ts
- packages/tests/package.json
- packages/tests/services/drag.spec.ts
Update happy-dom to the latest major version. This PR includes some refactors that were highlighted with this update.
> [Feature] Update happy-dom v14 → v15

- CHANGELOG.md
- packages/docs/.vitepress/config.js
- packages/docs/utils/createElement.md
- packages/js-toolkit/utils/dom/createElement.ts
- packages/js-toolkit/utils/dom/index.ts
- packages/tests/__utils__/h.ts
- packages/tests/utils/dom/createElement.spec.ts
- packages/tests/utils/index.spec.ts
This PR adds a new `createElement(tag, attributes, children)` function.
> [Feature] Add a `createElement` function

- CHANGELOG.md
- packages/js-toolkit/decorators/withBreakpointObserver.ts
- packages/js-toolkit/decorators/withDrag.ts
- packages/js-toolkit/decorators/withIntersectionObserver.ts
- packages/js-toolkit/decorators/withMountOnMediaQuery.ts
- packages/js-toolkit/decorators/withMountWhenInView.ts
- packages/js-toolkit/decorators/withRelativePointer.ts
- packages/js-toolkit/decorators/withScrolledInView/withScrolledInView.ts
- packages/tests/decorators/withIntersectionObserver.spec.ts
> [Feature] Refactor decorators to not change the configured name

- CHANGELOG.md
- packages/js-toolkit/services/DragService.ts
- packages/js-toolkit/utils/tween.ts
No issue.
This PR fixes a circular dependency.
> [Bugifx] Fix a circular dependency
